openapi: 3.0.0
info:
  description: This API allows you to retrieve and manage bicylce rentals.
  version: 1.0.0
  title: Bike Sharing API
tags:
  - name: Scoring
paths:
  /bikes:
    get:
      tags:
        - Bikes
      summary: Returns a list of all bikes
      operationId: getAllBikes
      parameters:
        - $ref: "#/components/securitySchemes/api_key"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BikeList"
        "400":
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "502":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - api_key: []
  /rent:
    post:
      tags:
        - Rental
      summary: Rent a bike by bike_id
      operationId: rentBike
      parameters:
        - $ref: "#/components/securitySchemes/api_key"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict - User already has an active rental session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - api_key: []

  /return:
    post:
      tags:
        - Rental
      summary: Provide a refund transaction to be processed by the billing
      operationId: storeRefund
      parameters:
        - $ref: "#/components/securitySchemes/api_key"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReturnResponse"
        description: todo
        required: true
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - api_key: []

  /initialize:
    post:
      tags:
        - Demo
      summary: Initialize data for demo purposes
      operationId: init
      responses:
        "200":
          description: Initialized successfully


servers:
  - url: https://bikerent.ndrshrzg.com/
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: apiKey
      in: header

  schemas:
    Bike:
      type: object
      properties:
        bike_id:
          type: string
        frame:
          type: string
        is_free:
          type: boolean
      required:
        - id

    BikeList:
      type: array
      items:
        $ref: '#/components/schemas/Bike'

    RentResponse:
      type: object
      properties:
        bike_id:
          type: string
        timestamp:
          type: number

    ReturnResponse:
      type: object
      properties:
        bike_id:
          type: string
        at:
          type: number

    ErrorResponse:
      type: object
      required:
        - statusCode
        - errorMessage
      properties:
        statusCode:
          type: integer
          format: int32
        errorMessage:
          type: string