openapi: 3.0.0
info:
  description: This API allows you to retrieve and manage bicylce rentals.
  version: 1.1.0
  title: Bike Sharing API
tags:
  - name: Scoring
paths:
  /bikes:
    get:
      tags:
        - Bikes
      summary: Receive a list of all bikes
      operationId: getAllBikes
      security:
        - basicAuth: [ ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BikeList"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /bikes/{bikeId}:
    get:
      tags:
        - Bikes
      summary: Receive info on a bike by bike_id
      operationId: getBikeByBikeId
      security:
        - basicAuth: [ ]
      parameters:
        - name: bikeId
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bike"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /rent/{bikeId}:
    post:
      tags:
        - Rental
      summary: Rent a bike by bike_id
      operationId: rentBike
      security:
        - basicAuth: [ ]
      parameters:
        - name: bikeId
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RentResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /return/{bikeId}:
    post:
      tags:
        - Rental
      summary: Return a bike by bike_id
      operationId: storeRefund
      security:
        - basicAuth: [ ]
      parameters:
        - name: bikeId
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReturnResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"



servers:
  - url: http://localhost

security:
  - basicAuth: [ ]

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    Bike:
      type: object
      properties:
        bike_id:
          type: number
        frame:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        is_free:
          type: boolean
      required:
        - id

    BikeList:
      type: array
      items:
        $ref: '#/components/schemas/Bike'

    RentResponse:
      type: object
      properties:
        message:
          type: string
        bike_id:
          type: number
        at_timestamp_milliseconds:
          type: number

    ReturnResponse:
      type: object
      properties:
        message:
          type: string
        bike_id:
          type: number
        at_timestamp_milliseconds:
          type: number
        session_duration_seconds:
          type: number

    ErrorResponse:
      type: object
      required:
        - statusCode
        - errorMessage
      properties:
        statusCode:
          type: integer
          format: int32
        errorMessage:
          type: string